name: Rust Build

on:
  push:
    branches: [ main, master ]
    paths:
      - 'rust/**'
      - '.github/workflows/rust-build.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'rust/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Windows AMD64
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          rust/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('rust/Cargo.lock') }}

    - name: Build
      working-directory: ./rust
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: aiclient2api-rust-windows-amd64
        path: rust/target/x86_64-pc-windows-msvc/release/aiclient2api-rust.exe
        retention-days: 30
